# Generated by Django 4.0.2 on 2022-03-09 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$'), django.core.validators.MinLengthValidator(2)])),
                ('msgText', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
